# Scalars, Vectors, and Matrices

## Introduction

A *scalar* is a number used to quantify magnitude (e.g. temperature), while a *vector* is a number used to quantify magnitude and direction (e.g. wind).  

Vectors are typically formatted as a list of numbers with each number corresponding to one direction. Familiar Cartesian coordinates have 2 dimensions, X & Y, and a vector in Cartesian coordinates is 1x2, a one dimensional list with two numbers. 
For example, west-east is the X axis and south-north is the Y axis. The vector (3, 4) indicates wind moving both 3 mph west and 4 mph north, but the combination of these components is a vector of wind moving 5 mph northwest (thanks to the pythagorean theorem, $a^2 + b^2 = c^2$). The magnitude is the distance from the origin (0,0), in this case 5. The vector itself is one dimensional and can be depicted as an arrow starting at (0,0) and extending to (3,4) in these Cartesian coordinates.    

***Note:*** A number with magnitude AND two or more directions is called a *tensor*. One way to think of a basic tensor is pinching and pulling a rubber sheet toward you: there is a magnitude of force pulling back toward the initial position (you could use this to launch a pebble like a slingshot) and there is also a magnitude of tension in the rubber sheet itself that will contract back when you let go. Tensors are used to describe gravity in general relativity.   

Vectors are typically formatted as one-dimensional data structures or lists, 1xN, with N as the length of the list.  A *matrix* is a two-dimensional, MxN, data structures. 

Here, we introduce common mathematical notation and the equivalent code implementation in [Numpy](https://numpy.org/).

**Numpy Setup:**

In [2]:
%%capture
!pip install numpy

import numpy as np

## Vector & Matrix Operations

### Notation
  
Like scalars, vectors and matrices of numbers can be added and multiplied. However, these operations differ from their scalar counterparts, and are heavily dependent on dimensionality. Matrix and vector dimensions are given as (r x c) where r is the number of rows, and c is the number of columns. Individual vectors are 1 dimensional and notated as a single row (1 x c) or as a single column (r x 1).

For example, $a$ is a [1x3] vector, called a row vector. Vector $b$ is a [3x1] vector, called a column vector. $C$ is a [3x3] matrix. The components of a matrix $C$ are denoted $c_{ij}$, where i is the row index and j is the column index.

***Note:*** Vectors are a special type of matrix. In the following sections, the term "matrices" will be used as a general term to refer to both matrices and vectors.
 
$$
\begin{equation}
a =
\left[
\begin{matrix}
a_{1} & a_{2} & a_{3}
\end{matrix}
\right]
;  b =
\left[
\begin{matrix}
b_{1} \\ b_{2} \\ b_{3}
\end{matrix}
\right]
; C =
\left[
\begin{matrix}
C_{11} & C_{12} & C_{13} \\ C_{21} & C_{22} & C_{23} \\ C_{31} & C_{32} & C_{33}
\end{matrix}
\right]
\end{equation}
$$

**Code:**

In [12]:
# Define vectors and matrices
a = np.array([[1, 2, 3]])        # Row vector (1x3)
b = np.array([[4], [5], [6]])    # Column vector (3x1)
c = np.array([[1, 2, 3],         # Matrix (3x3)
              [4, 5, 6],
              [7, 8, 9]])

# Get the dimensions
dim_a = a.shape
dim_b = b.shape
dim_c = c.shape

print(f'a({dim_a}):\n{a}')
print(f'b({dim_b}):\n{b}')
print(f'c({dim_c}):\n{c}')

a((1, 3)):
 [[1 2 3]]
b((3, 1)):
 [[4]
 [5]
 [6]]
c((3, 3)):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose
  
When performing operations on vectors, it is easiest to represent a vector as a column vector, and a corresponding row vector as its *transpose&. 
$$
\begin{equation}
a=
\left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
; a^T=
\left[
\begin{matrix}
a_{1} & a_{2} & a_{3}
\end{matrix}
\right]
\end{equation}
$$

**Code:**

In [13]:
# Define a row vector
a = np.array([[1, 2, 3]])

# Transpose the vector
a_transpose = a.T
print('Transpose of a:\n', a_transpose)
print(f'Dim a: {a.shape}')
print(f'Dim a_transpose: {a_transpose.shape}')

Transpose of a:
 [[1]
 [2]
 [3]]
Dim a: (1, 3)
Dim a_transpose: (3, 1)


### Addition
  
Matrices of the same dimension can be added component-wise, and the result is a new matrix of the same dimension.  

$$
\begin{equation}
\left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
+
\left[
\begin{matrix}
b_{1} \\ b_{2} \\ b_{3}
\end{matrix}
\right]
=
\left[
\begin{matrix}
a_{1} + b_{1}\\ a_{2} + b_{2} \\ a_{3} + b_{3}
\end{matrix}
\right]
\end{equation}
$$
  
Matrix subtraction works precisely the same way.

**Code:**

In [14]:
# Define two vectors
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# Calculate the sum of a and b
sum_ab = a + b

# Calculate the difference between b and a
diff_ba = b - a

print('a + b:\n', sum_ab)
print('b - a:\n', diff_ba)

a + b:
 [[5]
 [7]
 [9]]
b - a:
 [[3]
 [3]
 [3]]


### Scalar Multiplication

A matrix can also be multiplied by a scalar by multiplying every component of a matrix by that scalar.

$$
\begin{equation}
\alpha \left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
=
\left[
\begin{matrix}
\alpha a_{1} \\ \alpha a_{2} \\ \alpha a_{3}
\end{matrix}
\right]
\end{equation}
$$

**Code:**

In [ ]:


### Dot Product
  
However, there are other types of vector multiplication. Here, we will introduce one type of vector multiplication: the *dot product*, or *inner product*.  
  
A dot product is the sum of component-wise multiplication of vectors. To perform it, we first multiply each component of the first vector by its corresponding component of the second vector, then we sum the resulting products. The result of a dot product is a scalar.  
  
\begin{equation}
c =
\sum\limits_{i} a_{i} b_{i}
\end{equation}  
    
In vector notation, the dot product can be written as follows  
  
\begin{equation}
b \cdot a = b^T a = 
\left[
\begin{matrix}
b_{1} & b_{2} & b_{3}
\end{matrix}
\right]
\left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
=a_{1}b_{1} + a_{2}b_{2} + a_{3}b_{3}  
=c
\end{equation}  
  
Note that the product only works if its “inner dimensions”, the number of columns of $b$ and the number of rows of $a$, are the same.

## Exercise 1
 
What happens if we try to compute a dot product from vectors whose inner dimensions are different? Write some code in Python that tries to compute the dot product from vectors with different inner dimensions.  Report and interpret the error.

Here, you can use [Numpy](https://numpy.org/) for vector and matrix multiplication. To initialize a vecto
